### ISSUE TITLE
CMDI crosswalk is not working

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#610]
```
2024-04-04 09:15:00,636 ERROR unknown d4bd6bdf-f670-4367-b9c4-246fedfb558b org.dspace.xoai.controller.DSpaceOAIDataProvider @ A sequence of more than one item is not allowed as the first argument of fn:starts-with() ("#1-EuroMatrix Plus", "#2-Faust") 
com.lyncode.xoai.dataprovider.exceptions.OAIException: A sequence of more than one item is not allowed as the first argument of fn:starts-with() ("#1-EuroMatrix Plus", "#2-Faust") 
	at com.lyncode.xoai.dataprovider.handlers.ListRecordsHandler.createRecord(ListRecordsHandler.java:168) ~[xoai-3.4.0.jar:3.4.0]
	at com.lyncode.xoai.dataprovider.handlers.ListRecordsHandler.handle(ListRecordsHandler.java:124) ~[xoai-3.4.0.jar:3.4.0]
	at com.lyncode.xoai.dataprovider.OAIDataProvider.handle(OAIDataProvider.java:213) ~[xoai-3.4.0.jar:3.4.0]
	at org.dspace.xoai.controller.DSpaceOAIDataProvider.contextAction(DSpaceOAIDataProvider.java:131) [dspace-oai-7.6.1.jar:7.6.1]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
```

**Comment by MajoBerger** [comment]
The CMDI crosswalk must be reworked, to show the information correctly, as is the case in ufal.

**Comment by MajoBerger** [comment]
- https://lindat.mff.cuni.cz/repository/xmlui/handle/11234/1-1458
- https://lindat.mff.cuni.cz/repository/oai/request?verb=GetRecord&metadataPrefix=cmdi&identifier=oai:lindat.mff.cuni.cz:11234/1-1458
   - (`<ms:fundingProject>`)

- https://dev-5.pc:8443/handle/11234/1-1458
- https://dev-5.pc:8443/server/oai/request?verb=GetRecord&metadataPrefix=cmdi&identifier=oai:dev-5.pc:11234/1-1458

**Comment by MajoBerger** [comment]
find out more, why, how, what are the possibilities

**Comment by MajoBerger** [comment]
set max identifiers to more, to test all the items at once :) on top of `xoai.xml`
